# Generated by Django 4.0.4 on 2022-08-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_order_date_orderplaced_ordered_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'MOBILE'), ('L', 'LAPTOP'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('AC', 'ACCESSORIES'), ('FO', 'FOOTWEAR'), ('WO', 'WATCHES')], max_length=2),
        ),
    ]
