# Generated by Django 4.0.4 on 2022-08-28 14:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_slug_product_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
